
<html>
<head>
    <?php $this->partial("common/top");?>
    <link type="text/css" rel="stylesheet" href="/dist/css/bootstrap.css" />
    <title>最新新闻</title>
</head>
<body>
<div class="container">
<div class="list-group">
    <a href="#" class="list-group-item active">
        最新新闻
    </a>
    <?php if (is_array($news)): ?>
    <?php foreach ($news as $list): ?>
        <li><a href="newslist?id=<?php echo $list['id']; ?>" class="list-group-item"><?php echo mb_substr($list['newsTitle'], 0, 20); ?>
                <?php echo date('Y-m-d H:i:s', $list['newsTime']); ?></a></li>
    <?php endforeach;?>
    <?php endif;?>

</div>
<nav>
    <ul class="pagination">
        <?php echo $page; ?>
    </ul>
</nav>
    </div>
</body>
</html>

