<html xmlns="http://www.w3.org/1999/html">
<head>
    <?php $this->partial("common/top");?>
    <link type="text/css" rel="stylesheet" href="/dist/css/bootstrap.css" />
    <title >新闻详情</title>
    </head>
<body>
<div class="container">
    <ul class="list-group">
        <?php if (is_array($news)): ?>
        <?php foreach ($news as $row): ?>
        <li class="list-group-item" ><h2><strong><div class="text" style="text-align: center"><?php echo $row['newsTitle']; ?></div></strong></h2></li>
        <li class="list-group-item"><h5><div class="text" style="text-align: center">发布时间：<?php echo date("Y-m-d H:i:s", $row['newsTime']); ?></div></h5></li>
        <li class="list-group-item"><p><?php echo $row['newsContent']; ?></p></li>
    </ul>

    </div>
<div class="container">
    <div class="list-group">
<li class="list-group-item active">
         <h3> 评论区：</h3>
</li>
<?php if (is_array($comment)): ?>
        <?php foreach ($comment as $list): ?>


   <li class="list-group-item">
    <strong>评论标题：</strong><?php echo $list['commentTitle']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo date("Y-m-d H:i:s", $list['commentTime']); ?>
       </li>
        <li class="list-group-item">
       评论内容：<?php echo $list['commentContent']; ?>
   </li>
    <?php endforeach;?>
    <?php endif;?>
        <nav>
            <ul class="pagination">
                <?php echo $page; ?>
            </ul>
        </nav>

<form  action="commentadd" method="post">
    <br>
    <div class="input-group">
        <span class="input-group-addon" >评论标题：</span>
        <input type="text" class="form-control" name="title">
    </div>
    <br>
    <div class="input-group">
        <span class="input-group-addon">评论内容：</span>
        <input type="text" class="form-control"  name="content">
        <input type="hidden" class="form-control"  name="id" value="<?php echo $row['id']; ?>">
    </div>
    <br>
    <input style="right: auto" name="submit" value="评论" type="submit">
    <?php endforeach;?>
    <?php endif;?>
    </form>
</div>
    </body>
    </html>
