

<html>
<head>
    <?php $this->partial("common/top");?>
    <title>最新新闻</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <link href="/dist/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
    <link href="/dist/css/print.css" rel="stylesheet" type="text/css"  media="print" />
    <script src="js/jquery-1.10.1.min.js"></script>
    <script src="js/side.js" type="text/javascript"></script>
</head>
<body>
<div class="container">

        <ul class="nav nav-pills" role="tablist">
            <li role="presentation" class="active"><a href="/admin/default/index">最新新闻</a></li>
            <li role="presentation"><a href="/admin/comment/index">最新评论</a></li>
        </ul>

        <form action="search" method="post">
            <label for="orderId">新闻标题：</label>
            <input style="width:200px;" name="newstitle" id="orderId" type="text">
            <input name="submit" type="submit" class="btn btn-default btn-middle verti-middle-btn" value="搜索">
            <div class="text" style="text-align: right"> <a href="newsadd" >添加新文章</a></div>
        </form>

        <form action="delete" method="post">


                <!-----------------------循环读取最新公告信息------------------------>
            <div id="MainForm">
                <div class="form_boxA" >
                <table cellpadding="0" cellspacing="0">
                <tr>
                    <th>删除</th>
                    <th>新闻标题</th>
                    <th>新闻内容</th>
                    <th>创建时间</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                <?php if (is_array($news)): ?>
                <?php foreach ($news as $list): ?>
                <tr>
                    <a href="newslist?id=<?php echo $list['id']; ?>"></a>
                    <td> <input name="deleteid" value="<?=$list['id'];?>" class="checkbox" type="checkbox"></td>
                    <td ><a href="newslist?id=<?php echo $list['id']; ?>"><?php echo mb_substr($list['newsTitle'], 0, 20); ?></a></td>
                    <td><?php echo mb_substr($list['newsContent'], 0, 50); ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $list['newsTime']); ?></td>
                    <td><?php echo $list['newsStatus']; ?></td>
                    <td><a href="/admin/default/newsedit?id=<?=$list['id'];?>">编辑</a></td>
                </tr>
                    <?php endforeach;?>
                <?php endif;?>
</table>
     </div> </div>          <!-----------------------循环读取最新公告信息------------------------>

            <td><input value="提 交" class="btn" type="submit" name="submit"></td>
           </form>

    <nav style="float: right">
        <ul class="pagination">
            <?php echo $page; ?>
        </ul>
    </nav>
</div>

</body>
</html>
