<head>
    <?php $this->partial("common/top");?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>添加新文章</title>
    <!--前后顺序一定不能颠倒-->
    <script type="text/javascript"src="/utf8-php/ueditor.config.js"></script>
    <script type="text/javascript"src="/utf8-php/ueditor.all.min.js"></script>
    <script type="text/javascript"src="/utf8-php/lang/zh-cn/zh-cn.js"></script>
</head>
<body>
<div class="container">
    <div class="list-group">
        <li class="list-group-item active">
            <h2> 添加新文章：</h2>

        </li><br>
        <a href="index" >返回文章列表</a><br>
    <div class="mainbox">
        <!----------------------------添加新文章----------------------->
        <form action="/admin/default/newsadd" method="post">
            <table class="opt" style="width:600px;">
                <tbody>
                <div class="input-group">
                    <span class="input-group-addon">文章名称：</span>
                    <input type="text" class="form-control"  name="title">
                </div><br>
                <div class="input-group">
                    <span>文章内容：</span>
                <!-- 编辑器的使用  -->
                <script id="container" name="content" type="text/plain">
                            <?php echo $list['newsContent']; ?>
                        </script>
                <script type="text/javascript">
                    var ue = UE.getEditor('container');
                </script>
                </tbody>
            </table>
            <br>
            <div class="opt"><input name="submit" value=" 提 交 " class="btn" tabindex="3" type="submit"></div>
        </form>
        <!----------------------------添加新文章----------------------->
    </div>
</div>
</body>
</html>
