<head>
    <?php $this->partial("common/top");?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>添加新文章</title>
    <link rel="stylesheet" href="/admin/css/style.css" type="text/css" media="all">
</head>
<body>
<div class="container">
    <h3 class="marginbot">添加新文章<a href="index" class="sgbtn">返回文章列表</a></h3>
    <div class="mainbox">
        <!----------------------------添加新文章----------------------->
        <form action="/admin/default/newsedit" method="post">
            <table class="opt" style="width:600px;">
                <tbody>
                <?php if (is_array($news)): ?>
                <?php foreach ($news as $list): ?>
                        <tr><td><input name="id" value="<?php echo $list['id']; ?>" ></td></tr>
                <tr><th>文章名称：</th></tr>
                <tr><td><input name="title" value="<?php echo $list['newsTitle']; ?>" class="txt" style="width:400px;" type="text"></td></tr>
                <tr><th>文章内容：</th></tr>
                <tr><td><textarea name="content" style="width:400px; height:150px"  ><?php echo $list['newsContent']; ?></textarea></td></tr>

                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
            </table>
            <div class="opt"><input name="sub" value=" 提 交 " class="btn" tabindex="3" type="submit"></div>
        </form>
        <!----------------------------添加新文章----------------------->
    </div>
</div>
</body>
</html>
