<html xmlns="http://www.w3.org/1999/html">
<head>
    <?php $this->partial("common/top");?>

    <title >新闻详情</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <link href="/dist/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
    <link href="/dist/css/print.css" rel="stylesheet" type="text/css"  media="print" />
    <script src="js/jquery-1.10.1.min.js"></script>
    <script src="js/side.js" type="text/javascript"></script>
</head>
<body>
<div class="container">
    <div class="list-group">
        <li class="list-group-item active">
            <h3> 评论：</h3>
        </li>
        <form action="commentdelete" method="post">
            <div id="MainForm">
                <div class="form_boxA" >
                    <table cellpadding="0" cellspacing="0">
                        <tr>
                            <th>删除</th>
                            <th>评论标题</th>
                            <th>评论内容</th>
                            <th>创建时间</th>
                        </tr>
                        <?php if (is_array($comment)): ?>
                            <?php foreach ($comment as $list): ?>
                                <tr>
                                    <a href="newslist?id=<?php echo $list['id']; ?>"></a>
                                    <td ><input name="deleteid" value="<?=$list['id'];?>" class="checkbox" type="checkbox"></td>
                                    <td ><?php echo mb_substr($list['commentTitle'], 0, 20); ?></td>
                                    <td><?php echo mb_substr($list['commentContent'], 0, 50); ?></td>
                                    <td><?php echo date('Y-m-d H:i:s', $list['commentTime']); ?></td>
                                </tr>
                            <?php endforeach;?>
                        <?php endif;?>
                    </table>
                </div>
            </div><br>
            <td><input value="提 交" class="btn" type="submit" name="submit"></td>
        </form>
        <nav style="float: right">
            <ul class="pagination">
                <?php echo $page; ?>
            </ul>
        </nav>


    </div>
</body>
</html>
